# Copyright 2019-2025 Chris Croome
#
# This file is part of the Webarchitects skel Ansible role.
#
# The Webarchitects Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects skel Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects skel Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Skel profile www
  block:

    - name: "Skel directory present {{ skel_profile }}"
      ansible.builtin.file:
        path: "/usr/local/etc/skel.d/{{ skel_profile }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: "Skel private directories present {{ skel_profile }}"
      ansible.builtin.file:
        path: "/usr/local/etc/skel.d/{{ skel_profile }}/{{ skel_dir }}"
        state: directory
        owner: root
        group: root
        mode: "0700"
      loop:
        - .ansible/tmp
        - .cache
        - .composer
        - .config
        - .console
        - .drush
        - .git
        - .gnupg
        - .local
        - .moosh
        - .mutt
        - .mysql
        - .npm
        - .ssh
        - .terminfo
        - .vim
        - .wp-cli
        - .yarn
        - bin
        - private
        - tmp
      loop_control:
        loop_var: skel_dir
        label: "{{ skel_dir }}"

    - name: "Skel files in place {{ skel_profile }}"
      ansible.builtin.copy:
        src: "files/skel.d/{{ skel_profile }}/{{ skel_file }}"
        dest: "/usr/local/etc/skel.d/{{ skel_profile }}/{{ skel_file }}"
        owner: root
        group: root
        mode: "0600"
      loop:
        - .bash_logout
        - .bash_profile
        - .bashrc
        - .nanorc
        - .myclirc
        - .vimrc
        - .wp-cli/config.yml
      loop_control:
        loop_var: skel_file
        label: "{{ skel_file }}"

    - name: "Skel files touched for {{ skel_profile }}"
      ansible.builtin.file:
        path: "/usr/local/etc/skel.d/{{ skel_profile }}/{{ skel_file }}"
        state: touch
        owner: root
        group: root
        mode: "0600"
        modification_time: preserve
        access_time: preserve
      loop:
        - .bash_completion
        - .bash_history
        - .mycli-audit.log
        - .mycli-history
        - .mycli.log
        - .mysql/history
        - .rediscli_history
        - .redisclirc
        - .selected_editor
        - .valkeycli_history
        - .valkeyclirc
        - .yarnrc
      loop_control:
        loop_var: skel_file
        label: "{{ skel_file }}"

    - name: "Skel files absent for {{ skel_profile }}"
      ansible.builtin.file:
        path: "/usr/local/etc/skel.d/{{ skel_profile }}/{{ skel_file }}"
        state: absent
      loop:
        - .profile
      loop_control:
        loop_var: skel_file
        label: "{{ skel_file }}"

  tags:
    - skel
...
