---
- name: "Skel {{ skel }} directory present"
  file:
    path: "/usr/local/etc/skel.d/{{ skel }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - skel

- name: "Skel {{ skel }} files in place"
  copy:
    src: "files/skel.d/{{ skel }}/{{ file }}"
    dest: "/usr/local/etc/skel.d/{{ skel }}/{{ file }}"
    owner: root
    group: root
    mode: 0600
  loop:
    - .screenrc
  loop_control:
    loop_var: file
    label: "{{ file }}"
  tags:
    - skel

- name: "Skel {{ skel }} files touched"
  file:
    path: "/usr/local/etc/skel.d/{{ skel }}/{{ file }}"
    state: touch
    owner: root
    group: root
    mode: 0600
    modification_time: preserve
    access_time: preserve
  loop:
    - .xen-shell
  loop_control:
    loop_var: file
    label: "{{ file }}"
  tags:
    - skel
...
