---
- name: xen skel profile
  block:

    - name: "Skel {{ skel }} directory present"
      ansible.builtin.file:
        path: "/usr/local/etc/skel.d/{{ skel }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: "Skel {{ skel }} files in place"
      ansible.builtin.copy:
        src: "files/skel.d/{{ skel }}/{{ file }}"
        dest: "/usr/local/etc/skel.d/{{ skel }}/{{ file }}"
        owner: root
        group: root
        mode: "0600"
      loop:
        - .screenrc
      loop_control:
        loop_var: file
        label: "{{ file }}"

    - name: "Skel {{ skel }} private directories present"
      ansible.builtin.file:
        path: "/usr/local/etc/skel.d/{{ skel }}/{{ dir }}"
        state: directory
        owner: root
        group: root
        mode: "0700"
      loop:
        - .ssh
      loop_control:
        loop_var: dir
        label: "{{ dir }}"

    - name: "Skel {{ skel }} files touched"
      ansible.builtin.file:
        path: "/usr/local/etc/skel.d/{{ skel }}/{{ file }}"
        state: touch
        owner: root
        group: root
        mode: "0600"
        modification_time: preserve
        access_time: preserve
      loop:
        - .xen-shell
      loop_control:
        loop_var: file
        label: "{{ file }}"

  tags:
    - skel
...
